### PR TITLE
config: enable release-note for pd

### PR DESCRIPTION
**Pull request by CadmusJiang**
part of ti-community-infra/tichi#395

### CODE REVIEW

**Comment by CadmusJiang** [comment]
https://github.com/ti-community-infra/tichi/issues/395

**Comment by hi-rustin** [comment]
You need to modify the tide's query to prevent merging when the do-note-merge/release-note-label-needed label appears.

**Review by hi-rustin — APPROVED** [review]
/ok-to-test

**Comment by hi-rustin** [comment]
/hold

- [ ] update the pull request template of pd.

**Pull request merged**
