### PR TITLE
config: enable ti-community-label for ticdc

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Comment by hi-rustin** [comment]
cc: @amyangfei PTAL~

**Comment by hi-rustin** [comment]
Also it should be require-LGT3 instead of require-lgt3, please change it back.

**Comment by amyangfei** [comment]
> Also it should be require-LGT3 instead of require-lgt3, please change it back.

fixed @hi-rustin

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
