### PR TITLE
config: add qa-release-merge as a trusted team for the pd release branch

### PR DESCRIPTION
**Pull request by hi-rustin**
add qa-release-merge as a trusted team for the pd release branch.

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold 

Waiting pd team @nolouch  approve and merge.

**Comment by hi-rustin** [comment]
@jebter @zhouqiang-cl PTAL~

**Comment by jebter** [comment]
LGTM

**Review by rleungx — APPROVED** [review]

**Comment by hi-rustin** [comment]
@rleungx We only require one LGTM, you can merge it now.

**Pull request merged**
