### PR TITLE
config: add merge_commit_template for tikv

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/ti-community-infra/ti-community-prow/issues/255

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by Mini256 — APPROVED** [review]

**Comment by hi-rustin** [comment]
Waiting @Connor1996 @andylokandy approve.

**Review by Connor1996 — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Pull request merged**
