### PR TITLE
config: enable cherrypicker for dm

### PR DESCRIPTION
**Pull request by hi-rustin**
part of https://github.com/ti-community-infra/configs/issues/278

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

- [ ] Waiting for @amyangfei approve

- [ ] Waiting for @amyangfei modify labels

- [ ] Waiting for stop sre-bot service

**Comment by lance6716** [comment]
labels updated, example https://github.com/pingcap/dm/labels/needs-cherry-pick-release-2.0

/lgtm

**Pull request merged**
