### PR TITLE
chore: update the reviewer of chaos-mesh

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

Update the reviewer of Chaos Mesh with `include_reviewers`

### CODE REVIEW

**Comment by STRRL** [comment]
Sorry, I paste the list of reviewers in bad position, fixing. 😅

**Comment by STRRL** [comment]
PTAL, @hi-rustin @Mini256

**Review by hi-rustin — APPROVED** [review]
Thanks!

**Pull request merged**
