### PR TITLE
config: Add the v5.1 label for the docs-cn and docs repos

### PR DESCRIPTION
**Pull request by qiancai**
Signed-off-by: qiancai <qqzczy@126.com>

### CODE REVIEW

**Comment by hi-rustin** [comment]
You need to add this label to  https://github.com/ti-community-infra/configs/blob/0f0c4762bf6cbfb9e161407f9bd458d53e057e59/prow/config/external_plugins_config.yaml#L385

**Comment by qiancai** [comment]
> You also need to add this label to
> 
> https://github.com/ti-community-infra/configs/blob/0f0c4762bf6cbfb9e161407f9bd458d53e057e59/prow/config/external_plugins_config.yaml#L385

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
