### PR TITLE
config: add the bot configuration for v1.2 branch in the TiDB Operator Docs repo

### PR DESCRIPTION
**Pull request by qiancai**
There is a new branch release-1.2 for pingcap/docs-tidb-operator. This PR is to add the related bot configurations.

Branch: https://github.com/pingcap/docs-tidb-operator/tree/release-1.2

### CODE REVIEW

**Comment by Mini256** [comment]
We need to update the labels document after modifying `labels.yaml` config, you can fix it by running `scripts/update-labels.sh`.

This script requires `go` to be installed on the system, you can install using `brew install go`.

After the modification, you can re-trigger the test by command.

**Comment by qiancai** [comment]
> @qiancai, We need to update the labels document after modifying `labels.yaml` config, you can fix it by running `scripts/update-labels.sh`.
> 
> This script requires `go` to be installed on the system, you can install using `brew install go`.
> 
> After the modification, you can re-trigger the test by command.

Hi @Mini256 Thanks for the instructions. I've updated the script to update prow/config/labels.md. PTAL again.

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
