### PR TITLE
config: apply new tide template for tikv repos

### PR DESCRIPTION
**Pull request by Mini256**
part of https://github.com/tikv/community/issues/161

### CODE REVIEW

**Comment by Mini256** [comment]
@BusyJay @rleungx PTAL~

This PR will enable the commit message template and enable the format checker again to make sure all PR has at least one linked issue.

We will implement it in phases to transition from the past schema to the new one:

**Phase I (current)**:

- For the commit message, Tide will extract the linked issue numbers from the entire body range to the final commit message after merging (In the PR body, words like "refer to" and "part of" will be converted into the agreed keyword `ref`).
- The format checker, for now, only checks the PRs created on the master branch after 2022/2/1. (The new PR has already used the new PR template.)

**Phase II**:

- For the commit message, in order to avoid ambiguity, Tide will extract the linked issue numbers from the issue number line (which is started with `Issue Number: `) to the final commit message after merging.
- The format checker will check all PRs. 

cc: @zhangyangyu

**Comment by zhangyangyu** [comment]
This will also cancel the former rule requiring `close #xxx` in commit message right?

**Comment by Mini256** [comment]
> This will also cancel the former rule requiring `close #xxx` in commit message right?

The former requirement has been canceled on #494.

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
