### PR TITLE
feat(pingcap/kvproto): control reviewing approvals with prow OWNERS

### PR DESCRIPTION
**Pull request by wuhuizuo**
Signed-off-by: wuhuizuo <wuhuizuo@126.com>

### What problem does this PR solve?

Issue Number: ref pingcap/kvproto#1230

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/cc @tonyxuqqi
PTAL

/hold
depends on https://github.com/pingcap/kvproto/pull/1231

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
