### PR TITLE
config(tidb): enable ti-community-cherrypicker on `pingcap/tidb` repo

### PR DESCRIPTION
**Pull request by wuhuizuo**

### CODE REVIEW

**Review by Mini256 — COMMENTED** [review]
Don't forget to add plugin events dispatch config.

https://github.com/ti-community-infra/configs/blob/7ee6fd86e123a8bd75358448c4ff0c3e26094380/prow/config/plugins.yaml#L806

**Comment by wuhuizuo** [comment]
> Don't forget to add plugin events dispatch config.
> 
> https://github.com/ti-community-infra/configs/blob/7ee6fd86e123a8bd75358448c4ff0c3e26094380/prow/config/plugins.yaml#L806

done

**Comment by wuhuizuo** [comment]
`/merge` comment should be sent by me because of I need disable cherry pick in other bot.

**Review by purelind — APPROVED** [review]

**Pull request merged**
