### PR TITLE
config(ticdc): remove some required_status_checks in release-4.0

### PR DESCRIPTION
**Pull request by amyangfei**
Ref: https://github.com/pingcap/ticdc/pull/2409, `Lint` check has been removed.

Other checks are kept the same required_status_checks with release-5.0/release-5.1 and master branch in release-4.0.

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @hi-rustin , thanks

**Comment by Mini256** [comment]
@amyangfei, `Lint` required context has been removed in #388, could you mind resolve the conflict.

**Comment by hi-rustin** [comment]
I'm sorry, I didn't notice your PR, and then I removed the Lint by raising the PR myself.

ref: https://github.com/ti-community-infra/configs/pull/388

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
