### PR TITLE
config(tidb): prioritize the PRs with `Priority/P*` labels in merging queue

### PR DESCRIPTION
**Pull request by wuhuizuo**
Signed-off-by: wuhuizuo <wuhuizuo@126.com>

### What problem does this PR solve?

Issue Number: ref pingcap/tidb#41241

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### CODE REVIEW

**Comment by wuhuizuo** [comment]
For pingcap/tidb#47123

**Comment by wuhuizuo** [comment]
/hold

Should cancel the hold when https://github.com/pingcap/tidb/pull/47123 is approved and passed on CI jobs.

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
