### PR TITLE
config(tics): add required status unit-test

### PR DESCRIPTION
**Pull request by purelind**
releated to https://github.com/pingcap/tics/pull/3321
* tics has a new ci tics_ghpr_unit_test, so add required status unit-test

### CODE REVIEW

**Comment by purelind** [comment]
hold until https://github.com/pingcap/tics/pull/3321 merged

**Comment by solotzg** [comment]
Can we make /run-all-tests to trigger unit test in tics

**Comment by purelind** [comment]
> Can we make /run-all-tests to trigger unit test in tics

Yes, /run-all-tests and /run-unit-test (only when pr on branch master) will trigger unit-test ci in tics now

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
