### PR TITLE
add env label

### PR DESCRIPTION
**Pull request by jebter**

### CODE REVIEW

**Comment by Mini256** [comment]
I suggest we only use the `found/*` label or `source/*` label.  It is not a good idea to introduce a new label type when the `found/*` label type has been used.

In the real world, cockroachdb has provided us with good practice to reference.

image

@zhangyangyu @breeswish @tisonkun  @purelind, also look forward to your suggestion.

**Comment by breeswish** [comment]
I agree with @Mini256 . Looks like these labels can be merged together to express similar semantics.

In addition, I think current labels are too many. We'd better to only keep labels that are helpful for the issue list readers. If we want to carry metadata for our internal systems, then these metadata can be maintained internally.

**Comment by jebter** [comment]
It has nothing to do with tirelease and will be used in tibug. We can use found label, I will close this pr

**Pull request closed without merging**
