### PR TITLE
config: use English docs link

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Review by Mini256 — COMMENTED** [review]
Does the link `lgtm plugin design` need to update? (on line 227)

**Comment by hi-rustin** [comment]
> Does the link `lgtm plugin design` need to update? (on line 227)

No translation yet.

**Comment by Mini256** [comment]
> No translation yet.

😆  knowed

**Review by Mini256 — APPROVED** [review]
Does the link `lgtm plugin design` need to update? (on line 227)

**Pull request merged**
