### PR TITLE
config(docs-tidb-operator): add a label for type/compatibility change

### PR DESCRIPTION
**Pull request by ran-huang**
Add a `type/compatibility-or-feature-change` label for docs-tidb-operator.

### CODE REVIEW

**Comment by ran-huang** [comment]
@TomShawn PTAL, thanks!

**Comment by TomShawn** [comment]
You might also need to update https://github.com/ti-community-infra/configs/blob/main/prow/config/labels.md accordingly. It is recommended to run https://github.com/ti-community-infra/configs/blob/main/scripts/update-labels.sh that automatically updates  `labels.md`. Runnning this script requires a Golang environment.

**Comment by ran-huang** [comment]
@TomShawn Thanks for the reminder. I'm a bit confused, though. Is there any documented procedure for how to add labels?

**Comment by Mini256** [comment]
>  Is there any documented procedure for how to add labels?

Not yet, I will update it on the [plugin document](https://book.prow.tidb.io/#/tools/label_sync).

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
