### PR TITLE
config: add release-1.3 branch config for docs-tidb-operator repo

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

Add branch config for release-1.3 branch of docs-tidb-operator.

### CODE REVIEW

**Comment by ran-huang** [comment]
@TomShawn PTAL. Thanks!

**Comment by TomShawn** [comment]
LGTM

**Review by Mini256 — COMMENTED** [review]
Please add the `needs-cherry-pick-release-1.3` label to the whitelist of the labels plugin for contributors.
https://github.com/ti-community-infra/configs/blob/69aa0cdef49aa2835ef3ba94406ad62527dee72c/prow/config/external_plugins_config.yaml#L639

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
