### PR TITLE
config(tikv/tikv): auto apply to milestone for new pull request

### PR DESCRIPTION
**Pull request by wuhuizuo**
- enable plugins: `milestone` and `milestoneapplier`.
- config plugin configuratioins.

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### CODE REVIEW

**Comment by wuhuizuo** [comment]
ping @purelind

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
