### PR TITLE
config: enable auto-cc for docs sig

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

Under this config, tichi auto-cc TomShawn in docs and docs-cn, Charlotteiu in docs-dm, yikeke in docs-tidb-operator.

### CODE REVIEW

**Comment by ran-huang** [comment]
@yikeke @qiancai PTAL

**Comment by hi-rustin** [comment]
@Mini256  Maybe we need to add an include_reviewers configuration item?

What do you think?

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
