### PR TITLE
config: enforce CLA checking for tiflash

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Signed-off-by: SchrodingerZhu <i@zhuyi.fan>

### CODE REVIEW

**Comment by solotzg** [comment]
LGTM

**Comment by solotzg** [comment]
@Mini256 PTAL

**Review by Mini256 — APPROVED** [review]

**Comment by Mini256** [comment]
@solotzg, why do we use DCO instead of CLA?

**Comment by solotzg** [comment]
> @solotzg, why do we use DCO instead of CLA?

Maybe tiflash should be consistent with `tidb` and use `CLA`

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
