### PR TITLE
config(tiflow): add area/engine label to tiflow repo

### PR DESCRIPTION
**Pull request by amyangfei**
ref task-2 in https://github.com/pingcap/tiflow/issues/5352

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @Mini256

**Review by Mini256 — APPROVED** [review]

**Comment by amyangfei** [comment]
CI has passed, please help to trigger merge, thanks! @Mini256

**Comment by Mini256** [comment]
@amyangfei Done. Sorry to forget it.

**Pull request merged**
