### PR TITLE
config: add labels for 4 docs repos

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

- Add SIG labels for 4 docs repos.
- Delete some outdated labels.
- Add description for all labels.

### CODE REVIEW

**Comment by ran-huang** [comment]
@yikeke PTAL

**Comment by hi-rustin** [comment]
@ran-huang I don't recommend that you enable the help plugin now, because the help plugin uses a link to the documentation from k8s in its reply. It is configurable, but the tidb community does not have such a document yet.  See: https://github.com/ti-community-infra/tichi/issues/465#issuecomment-814577775.

**Comment by hi-rustin** [comment]
Or if you feel that the requirements in this document are reasonably acceptable, it's okay to enable the plugin. If you want to enable it, please modify the PR title to add this part of the change.

**Comment by ran-huang** [comment]
> @ran-huang I don't recommend that you enable the help plugin now, because the help plugin uses a link to the documentation from k8s in its reply. It is configurable, but the tidb community does not have such a document yet. See: [ti-community-infra/tichi#465 (comment)](https://github.com/ti-community-infra/tichi/issues/465#issuecomment-814577775).

@rustin-bot OK. Is there a plugin that helps us manually trigger tests (Circle CI and CLA checks)

**Comment by hi-rustin** [comment]
> > @ran-huang I don't recommend that you enable the help plugin now, because the help plugin uses a link to the documentation from k8s in its reply. It is configurable, but the tidb community does not have such a document yet. See: [ti-community-infra/tichi#465 (comment)](https://github.com/ti-community-infra/tichi/issues/465#issuecomment-814577775).
> 
> @rustin-bot OK. Is there a plugin that helps us manually trigger tests (Circle CI and CLA checks)

No, because we had difficulty adapting to Circle CI and PingCAP's CLA.

**Review by yikeke — APPROVED** [review]
/lgtm

**Pull request merged**
