### PR TITLE
 config: add release 5.1 config

### PR DESCRIPTION
**Pull request by Mini256**
add release 5.1 config for:

- pingcap/tidb
- tikv/tikv
- tikv/pd
- pingcap/br
- pingcap/tidb-tools
- pingcap/ticdc
- pingcap/dumpling

### CODE REVIEW

**Comment by Mini256** [comment]
@hi-rustin PTAL~

cc: @zhouqiang-cl

**Comment by hi-rustin** [comment]
Thanks!

I will take a look tomorrow. @zhouqiang-cl Could you also confirm that these branches and CIs are correct? Thanks!

/assign

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
@Mini256  Thanks!

/merge

**Pull request merged**
