### PR TITLE
ci: add ti-community-bot jobs

### PR DESCRIPTION
**Pull request by hi-rustin**
We'll add these tasks and leave the GitHub actions in place for now, and add codecov and remove GitHub actions after we've made sure they're okay.

cc: https://github.com/ti-community-infra/ti-community-bot/issues/275

### CODE REVIEW

**Comment by hi-rustin** [comment]
/assign @Mini256 

PTAL~ Thanks!

**Review by Mini256 — COMMENTED** [review]
What will be used instead of `npx codecov` in the current workflow?

**Comment by hi-rustin** [comment]
> What will be used instead of `npx codecov` in the current workflow?

See my PR body. I will add the codecov-related scripts after testing that it works.

**Comment by Mini256** [comment]
/lgtm

OK.

**Pull request merged**
