### PR TITLE
add: do not need-cherry-pick label version list

### PR DESCRIPTION
**Pull request by VelocityLight**
# Why
Disable the bot's automatic "need-cherry-pick" label to avoid too many PRs being created automatically. The related behavior will be moved to tirelease, where users can manually operate or use bot commands to add the "need-cherry-pick" label and create PRs as needed.

The PR will make some changes for tidb component label actions
--------
# Not changed parts
The actions after adding the "need-cherry-pick" label remain the same, but the bot will no longer automatically add the label. However, if the user adds the "need-cherry-pick" label by other means, the bot will still create the corresponding PR as before, and its behavior will remain unchanged.

### CODE REVIEW

**Review by purelind — APPROVED** [review]
/lgtm

**Comment by wuhuizuo** [comment]
/hold

Need more LGTMs from repo owners.

**Pull request closed without merging**
