### PR TITLE
config: add branch-protection and  context_options to the release branch of PD

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: HunDunDM <hundundm@gmail.com>

* config: add branch-protection to the release branch of PD
* config: add context_options to the release branch of PD

### CODE REVIEW

**Comment by HunDunDM** [comment]
@nolouch PTAL

**Comment by hi-rustin** [comment]
Now you sig people have permission.

**Comment by hi-rustin** [comment]
@HunDunDM Maybe you need a force push to wake up the Semantic Pull Request bot.

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
