### PR TITLE
chore(prow/config): remove dmr versions from triage list

### PR DESCRIPTION
**Pull request by wuhuizuo**
also add old no-dmr to wont fix list.

Signed-off-by: wuhuizuo <wuhuizuo@126.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### CODE REVIEW

**Review by jebter — APPROVED** [review]

**Review by MimeLyc — APPROVED** [review]

**Review by VelocityLight — APPROVED** [review]

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
