### PR TITLE
config: add sig prefix for docs sig repos

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

### CODE REVIEW

**Comment by hi-rustin** [comment]
@ran-huang  Have you added the sig-related labels to your repository yet?

**Comment by ran-huang** [comment]
> @ran-huang Have you added the sig-related labels to your repository yet?

Thanks for the reminder. @yikeke will add them.

**Comment by hi-rustin** [comment]
> > @ran-huang Have you added the sig-related labels to your repository yet?
> 
> Thanks for the reminder. @yikeke will add them.

We already have a tool to help maintain the label, which can be enabled if you need to change the tool.

https://book.prow.tidb.io/#/tools/label_sync

**Comment by ran-huang** [comment]
> > > @ran-huang Have you added the sig-related labels to your repository yet?
> > 
> > 
> > Thanks for the reminder. @yikeke will add them.
> 
> We already have a tool to help maintain the label, which can be enabled if you need.
> 
> https://book.prow.tidb.io/#/tools/label_sync

@hi-rustin Great! Can you help us enable it?

**Review by yikeke — APPROVED** [review]

**Comment by hi-rustin** [comment]
> @hi-rustin Great! Can you help us enable it?

Maybe next week.

**Comment by ran-huang** [comment]
> > @hi-rustin Great! Can you help us enable it?
> 
> Maybe next week.

@hi-rustin a friendly ping 🙌

**Pull request merged**
