### PR TITLE
config: add release-6.0

### PR DESCRIPTION
**Pull request by purelind**
add new branch release-6.0

### CODE REVIEW

**Review by Mini256 — COMMENTED** [review]
missing affects-6.0 on tiflow repo, rest LGTM

https://github.com/ti-community-infra/configs/blob/441568cf5113afa409e10b2843da9551a4883702/prow/config/external_plugins_config.yaml#L828

**Comment by purelind** [comment]
> missing affects-6.0 on tiflow repo, rest LGTM
> 
> https://github.com/ti-community-infra/configs/blob/441568cf5113afa409e10b2843da9551a4883702/prow/config/external_plugins_config.yaml#L828

fix this.

**Review by Mini256 — APPROVED** [review]

**Comment by Mini256** [comment]
/merge
/hold

Feel free to `/unhold` when the new branch was checkouted.

**Pull request merged**
