### PR TITLE
config: add restrictions to tikv and tidb release branchs

### PR DESCRIPTION
**Pull request by hi-rustin**
For the release branch, we want to strictly restrict push permissions.

### CODE REVIEW

**Comment by hi-rustin** [comment]
/assign @Mini256 

PTAL~

**Review by Mini256 — COMMENTED** [review]
Should tidb:release-3.0 be restricted?

**Comment by hi-rustin** [comment]
> Should tidb:release-3.0 be restricted?

Good catch! Thanks!

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
